import Head from 'next/head'

import styles from '../styles/Home.module.css'
import MainLayout from "../components/layouts/MainLayout";
import {useState} from "react";
import axios from "axios";
import Slider from "../components/website/Slider";
import VendorLogos from "../components/website/VendorLogos";



export default function Home({images}) {


    const [sale, setSale] = useState(false)




    return (



        <div className={styles.container}>


            <Head>
                <title>RnG Diving</title>

                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Slider images={images} as={'image'}/>
            <VendorLogos images={images} as={'logo'} />
        </div>

    )
}
export async function getServerSideProps (){
    //const host = ctx.req.headers.host;


    const res = await axios.get(process.env.PUBLIC_URL+`/api/images`);

    return{
        props:{
            images: res.data
        }
    }
}
Home.getLayout = function getLayout(page){
    return(
        <MainLayout>
            {page}
        </MainLayout>
    )
}
