import Head from 'next/head'
import {getSession} from "next-auth/react";
import styles from '../styles/Home.module.css'
import MainLayout from "../components/layouts/MainLayout";
import {useEffect, useState} from "react";
import axios from "axios";
import Slider from "../components/website/Slider";
import VendorLogos from "../components/website/VendorLogos";
import { getCookies, getCookie, setCookies, removeCookies } from 'cookies-next';
import { v4 as uuidv4 } from 'uuid';





export default function Home({images}) {

    const [sale, setSale] = useState(false)





    return (



        <div className={styles.container}>


            <Head>
                <title>RnG Diving</title>

                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/headerlogo.svg"/>
            </Head>
            <Slider images={images} as={'image'}/>
            <VendorLogos images={images} as={'logo'} />
        </div>

    )
}
export async function getServerSideProps ({req, res}){

    const {host} = req.headers;

    const pic = await axios.get(`https://`+host+`/api/images`);
    setCookies('visitor', `guest${uuidv4()}`, { req, res, maxAge: 60 * 6 * 24 });

    return{
        props:{
            images: pic.data,


        }
    }
}


Home.getLayout = function getLayout(page){
    return(
        <MainLayout>
            {page}
        </MainLayout>
    )
}


